aws_profile    = "default"
aws_region     = "us-east-1"
vault_ami      = "ami-098f16afa9edf40be"
instance_type  = "t2.micro"
avail_zone     = "us-east-2a"
s3_bucket      = "s3-backend-vishnu"
inst_vol_size  = "15"
inst_vol_type  = "gp2"
